Add optional notifications support through SNS
lgallard/terraform-aws-backup pull request #19
Opened 2021-02-13 02:18 UTC by diego-ojeda-binbash

2021-02-13 11:36 UTC, exequielrafaela approved these changes

2021-02-13 11:56 UTC, exequielrafaela commented
@diego-ojeda-binbash OJ If I've understood correctly, on the one hand, this new feature creates the SNS topic with all the necessary resources so a subscriber can get the notification. On the other hand, it would be very useful to have the possibility to **optionally** pass a pre-existing SNS topic arn like the one resulting from https://github.com/binbashar/terraform-aws-notify-slack that we frequently use. Equivalent to our CloudTrail and Config notifications setup, which would probably be the approach we will take for the backup service too.

I've already approved it ✅, may be we could extend it in this PR, or a new one.

Thanks for your continuous and effortless collaboration!!! 🚀 💪🏼 👏🏼

2021-02-14 16:50 UTC, lgallard commented
@diego-ojeda-binbash I'd rather separate resources not related to the main function (in this cases AWS Backup) and instead pass the "external" resources (in this example, the SNS topic arn) as an module input. 

Why? It's more difficult to keep track of resources changes/evolution of each resource and fix or enhance them.

To be honest, I like the idea of adding a SNS topic in case you don't have one, but I agree with @exequielrafaela on the fact that it would be useful to pass an external SNS topic arn in case you had already created it from other services / logic.

2021-02-14 17:09 UTC, lgallard requested changes

2021-02-14 17:09 UTC, lgallard commented on notifications.tf
> +resource "aws_sns_topic" "backup_events" {
I'd rather leave all the SNS code outside the module

2021-02-14 17:09 UTC, lgallard commented on notifications.tf
> +  sns_topic_arn       = aws_sns_topic.backup_events[0].arn
Once the SNS topic was created outside this module, pass the ARN here, using the SNS resource or module output as the input of this module

2021-02-14 17:09 UTC, lgallard commented on variables.tf
> +variable "notifications_backup_vault_events" {
I agree on this variable definition

2021-02-14 17:09 UTC, lgallard commented on variables.tf
> +variable "notifications_sns_topic_name" {
But the SNS variable would go outside the module

2021-02-15 17:07 UTC, diego-ojeda-binbash commented
@exequielrafaela @lgallard Thanks for all your comments! After careful thinking I believe it would be best to move this functionality to a separate module where can also handle the use case that @exequielrafaela suggested. That way, the new module will be able to handle both fan-in and fan-out messaging strategies instead of being constrained to only one of them.

2021-02-15 17:07 UTC, closed without merging

2021-02-28 21:44 UTC, lgallard commented
@diego-ojeda-binbash @exequielrafaela release 0.7.0 has an implementation based on this PR. Now you can define notifications as follows:

```
module "aws_backup_example" {

  source = "lgallard/backup/aws"

  # Vault
  vault_name = "vault-3"

  # Plan
  plan_name = "complete-plan"

  # Notifications
  notifications = {
    sns_topic_arn       = aws_sns_topic.backup_vault_notifications.arn
    backup_vault_events = ["BACKUP_JOB_STARTED", "BACKUP_JOB_COMPLETED", "BACKUP_JOB_FAILED", "RESTORE_JOB_COMPLETED"]
  }
```

Use `sns_topic_arn` to pass an already created SNS topic by a resource or a module as mentioned by @exequielrafaela (/terraform-aws-notify-slack module)